"""The library scout's candidate files (issue #227).

:func:`render` writes one self-contained candidate per adapter and target:

* a docstring that says what it is (generated, not an agent's), which families the reference
  calls, which configs the scout sweeps and whether the template ran on a GPU yet;
* ``KA_LIBRARY = "<package>@<version>"`` (the ledger's backend ``library:<package>@<version>``,
  :func:`kernel_agent.ledger.detect_backend`; the export's ``requirements.txt``),
  ``KA_LICENCE``, and ``ARCHS`` / ``ARCHS_WHY`` like the bundled examples;
* the graph rewrite helpers it needs, copied from :mod:`kernel_agent.libscout.fx_rewrites`;
* the adapter's op code (:meth:`Adapter.code`): ``ops(reference, **config)`` and
  ``rewrite(graph, reference, **config)``;
* ``LibraryScout``: the reference's captured entrypoints compiled by TorchDynamo with a
  backend that runs ``rewrite`` on each FX graph and then runs the graph eagerly (no
  Inductor), and ``build(reference, <config>=<default>, ...)``.

The reference's Python code does not run (Dynamo runs its graph), so the evaluator's fallback
check judges the kernels: a candidate that launches only the reference's kernels is a
``fallback``, one with library kernels has ``custom_kernel_share`` > 0.
"""

from __future__ import annotations

import inspect
import keyword
import re
from collections.abc import Iterable, Mapping
from typing import Any

from kernel_agent.libscout import fx_rewrites
from kernel_agent.libscout.registry import Adapter

#: Dynamo's recompile limits the candidate raises (one compile per module instance and
#: input shape: an integration builds one candidate per layer).
RECOMPILE_LIMIT = 256
ACCUMULATED_LIMIT = 4096

_SCAFFOLD = '''

class LibraryScout(nn.Module):
    """The reference's entrypoints compiled by TorchDynamo with ``rewrite`` applied to each
    FX graph, which then runs eagerly (no Inductor): only the rewritten nodes change."""

    def __init__(self, reference, config):
        super().__init__()
        self.reference = reference  # its weights and state, shared
        self.rewritten = 0  # graph nodes ``rewrite`` changed (0: the library runs nowhere)

        def compile_graph(gm, example_inputs):
            self.rewritten += rewrite(gm.graph, reference, **config)
            gm.graph.lint()
            gm.recompile()
            return gm.forward

        self._compiled = {{
            name: torch.compile(getattr(reference, name), backend=compile_graph)
            for name in METHODS
        }}
{methods}

def build(reference{params}):
    """The scout's candidate: {title}."""
    limits = torch._dynamo.config
    limits.recompile_limit = max(limits.recompile_limit, {limit})
    limits.accumulated_recompile_limit = max(limits.accumulated_recompile_limit, {total})
    prepare(reference)
    return LibraryScout(reference, {config})
'''

_METHOD = """
    def {name}(self, *args, **kwargs):
        return self._compiled["{name}"](*args, **kwargs)
"""


def _identifier(name: str) -> bool:
    return name.isidentifier() and not keyword.iskeyword(name)


def config_keys(configs: Iterable[Mapping[str, Any]]) -> list[str]:
    """The keyword arguments the configs set, in first-seen order."""
    keys: dict[str, None] = {}
    for config in configs:
        for key in config:
            keys.setdefault(str(key), None)
    return list(keys)


def render(
    adapter: Adapter,
    *,
    target: str,
    version: str | None,
    configs: list[dict[str, Any]],
    families: str = "",
    methods: Iterable[str] = ("forward",),
) -> str:
    """The candidate file of ``adapter`` for ``target`` (see the module docstring); the
    first config gives ``build``'s defaults."""
    methods = [m for m in dict.fromkeys(["forward", *methods]) if _identifier(m)]
    keys = config_keys(configs)
    first = configs[0] if configs else {}
    params = "".join(f", {k}={first.get(k)!r}" for k in keys if _identifier(k))
    config = "{" + ", ".join(f"{k!r}: {k}" for k in keys if _identifier(k)) + "}"
    label = f"{adapter.package}@{version or 'unknown'}"
    swept = "; ".join(", ".join(f"{k}={v!r}" for k, v in c.items()) or "default" for c in configs)
    verified = (
        "Verified: this template ran on a GPU in kernel-agent's tests."
        if adapter.verified
        else f"Not verified on a GPU yet: written from {adapter.package}'s documentation "
        "(the library was not installed where kernel-agent was developed)."
    )
    doc = (
        f'"""Library scout candidate for target `{target}`: {adapter.title}.\n\n'
        f"Generated by kernel-agent's library scout (``kernel_agent/libscout``, adapter "
        f"``{adapter.name}``), not by an agent. TorchDynamo traces the reference's own "
        "entrypoints into FX graphs; ``rewrite`` points the library's ops into them; the "
        "graphs run eagerly (no Inductor), so every other op launches the reference's own "
        "kernels and the evaluator's fallback check passes only when the library's kernels "
        "differ from the reference's (``custom_kernel_share`` > 0).\n\n"
        f"The reference calls (one captured case): {families or 'see spec.json'}.\n"
        f"Configs swept by the scout (``build`` keyword arguments): {swept}.\n"
        f"{verified}\n\n"
        "Dynamo checks its guards on every call (host time: tens of microseconds on a busy "
        "CPU), so a launch-bound target pays for it; inside a CUDA graph it is gone. The "
        "library call itself can go into a hand-written module instead.\n"
        '"""\n'
    )
    head = [
        doc,
        "from __future__ import annotations",
        "",
        "import operator",
        "",
        "import torch",
        "import torch._dynamo",
        "from torch import nn",
        "",
        f"KA_LIBRARY = {label!r}  # the ledger's backend: library:<package>@<version>",
        f"KA_LICENCE = {adapter.licence!r}",
        f"KA_ADAPTER = {adapter.name!r}",
    ]
    if adapter.archs:
        head.append(f"ARCHS = {adapter.archs!r}")
        head.append(f"ARCHS_WHY = {adapter.archs_why!r}")
    head.append(f"METHODS = {tuple(methods)!r}  # the captured entrypoints")
    helpers = [inspect.getsource(fx_rewrites.HELPERS[h]) for h in _helpers(adapter)]
    code = adapter.code().strip("\n")
    if not re.search(r"^def prepare\(", code, re.M):
        code += '\n\n\ndef prepare(reference):\n    """Nothing to build before timing."""\n'
    scaffold = _SCAFFOLD.format(
        methods="".join(_METHOD.format(name=m) for m in methods),
        params=params,
        title=adapter.title,
        limit=RECOMPILE_LIMIT,
        total=ACCUMULATED_LIMIT,
        config=config,
    )
    body = "\n\n".join(h.strip("\n") for h in helpers)
    text = "\n".join(head) + "\n\n\n" + body + "\n\n" + code.rstrip() + "\n\n" + scaffold
    return re.sub(r"\n{4,}", "\n\n\n", text).rstrip() + "\n"


def _helpers(adapter: Adapter) -> list[str]:
    """The helper functions the adapter's code calls (``swap_calls`` always: the
    simplest rewrite, and the one most adapters use)."""
    names = ["swap_calls", *adapter.helpers]
    return [n for n in dict.fromkeys(names) if n in fx_rewrites.HELPERS]


def library_of(source: str) -> str | None:
    """``<package>@<version>`` of a candidate's ``KA_LIBRARY`` line (None: not a scout
    candidate, or one written by hand that declares none)."""
    match = re.search(r"""^KA_LIBRARY\s*=\s*['"]([^'"\n]+)['"]""", source, re.M)
    return match.group(1) if match else None


def licence_of(source: str) -> str | None:
    match = re.search(r"""^KA_LICENCE\s*=\s*['"]([^'"\n]+)['"]""", source, re.M)
    return match.group(1) if match else None
